In [1]:
import pandas as pd
import numpy as np

In [2]:
inflation = pd.read_csv('../data/raw/inflation.csv', skiprows=4)
chomage = pd.read_csv('../data/raw/chomage.csv', skiprows=4)
pib = pd.read_csv('../data/raw/pib.csv', skiprows=4)

In [9]:
def nettoyer_indicateur(df, nom_colonne, annee_debut=2000, annee_fin=2024):
    
    colonnes_annees = [str(a) for a in range(annee_debut, annee_fin + 1)]
    colonnes_annees = [c for c in colonnes_annees if c in df.columns]

    df_maroc = df[df['Country Name'] == 'Morocco'][colonnes_annees]

    serie = df_maroc.T
    serie.columns = [nom_colonne]
    serie.index = serie.index.astype(int)
    serie = serie.sort_index()
    serie[nom_colonne] = pd.to_numeric(serie[nom_colonne], errors='coerce')

    return serie

In [8]:
inflation_t = nettoyer_indicateur(inflation, 'inflation_pct')
chomage_t = nettoyer_indicateur(chomage, 'chomage_pct')
pib_t = nettoyer_indicateur(pib, 'pib')

inflation_t.head()

      inflation_pct
2000       1.894635
2001       0.619802
2002       2.795620
2003       1.167734
2004       1.493444

In [13]:
df = pd.concat([pib_t, inflation_t, chomage_t], axis=1)
df.head(10)

               pib  inflation_pct  chomage_pct
2000  4.301746e+10       1.894635        13.58
2001  4.383148e+10       0.619802        12.46
2002  4.707719e+10       2.795620        11.59
2003  5.802936e+10       1.167734        11.92
2004  6.611415e+10       1.493444        10.83
2005  6.885266e+10       0.982642        11.01
2006  7.588382e+10       3.284762         9.67
2007  8.694791e+10       2.042085         9.56
2008  1.018229e+11       3.714843         9.57
2009  1.011550e+11       0.971863         8.96

In [14]:
print("Valeurs manquantes par colonne :")
print(df.isnull().sum())

Valeurs manquantes par colonne :
pib              0
inflation_pct    0
chomage_pct      0
dtype: int64

In [15]:
df = df.interpolate(method='linear')
print("Valeurs manquantes après traitement :")
print(df.isnull().sum())

Valeurs manquantes après traitement :
pib              0
inflation_pct    0
chomage_pct      0
dtype: int64

In [16]:
df.to_csv('../data/processed/donnees_economiques_maroc.csv')
print("Fichier sauvegardé avec succès.")
df.tail()

Fichier sauvegardé avec succès.

               pib  inflation_pct  chomage_pct
2020  1.213536e+11       0.705969       11.189
2021  1.420221e+11       1.401959       10.551
2022  1.312453e+11       6.657042        9.413
2023  1.460361e+11       6.091142        8.896
2024  1.606110e+11       0.985257        9.103